spring:
  application:
    name: ai-knowledge-assistant

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_knowledge_assistant
    username: postgres
    password: 1111


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true

jwt:
  secret: 67R6r7Ma/T+jP8EacBFA0Rr8uqSUJCppSZult/YoiFIQUaJQuu27MBgt1zk6Ym170qLOkvkXgHMNw/dxOuw84w==
  expiration: 86400000

server:
    port: 8080
